/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package im.bci.nanimstudio;

import im.bci.nanimstudio.model.NanimStudioModel;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bob
 */
public class NanimStudioMainWindow extends javax.swing.JFrame {

    private final NanimStudioModel nanimStudio;
    private File lastFile;

    /**
     * Creates new form NanimStudioMainWindow
     */
    public NanimStudioMainWindow() {
        nanimStudio = NanimStudioModel.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        nanim = nanimStudio.getNanim();
        nimagesEditor = new im.bci.nanimstudio.NimagesEditor();
        nanimationEditor = new im.bci.nanimstudio.NanimationEditor();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nFramesEditor1 = new im.bci.nanimstudio.NframesEditor();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem_new = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_importGIF = new javax.swing.JMenuItem();
        jMenuItem_exportGIF = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        getContentPane().add(nimagesEditor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(nanimationEditor, gridBagConstraints);

        jLabel1.setText("Images");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Animations");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Frames");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel3, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, nanimationEditor, org.jdesktop.beansbinding.ELProperty.create("${selectedAnimation}"), nFramesEditor1, org.jdesktop.beansbinding.BeanProperty.create("animation"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(nFramesEditor1, gridBagConstraints);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        jMenuItem_new.setText("New");
        jMenuItem_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_newActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem_new);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(jSeparator1);

        jMenuItem_importGIF.setText("Import GIF...");
        jMenuItem_importGIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_importGIFActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem_importGIF);

        jMenuItem_exportGIF.setText("Export GIF...");
        jMenuItem_exportGIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exportGIFActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem_exportGIF);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_newActionPerformed
        nanim.clear();
        lastFile = null;
    }//GEN-LAST:event_jMenuItem_newActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        JFileChooser chooser = new JFileChooser(nanimStudio.getPreferences().get("lastNanimDirectory", null));
        chooser.setFileFilter(new FileNameExtensionFilter("nanim animations", "nanim", "nanim"));
        if (JFileChooser.APPROVE_OPTION == chooser.showSaveDialog(this)) {
            nanimStudio.getPreferences().put("lastNanimDirectory", chooser.getCurrentDirectory().getAbsolutePath());
            nanim.saveAs(chooser.getSelectedFile());
            lastFile = chooser.getSelectedFile();
        }
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        if (null != lastFile) {
            nanim.saveAs(lastFile);
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        JFileChooser chooser = new JFileChooser(nanimStudio.getPreferences().get("lastNanimDirectory", null));
        chooser.setFileFilter(new FileNameExtensionFilter("nanim animations", "nanim", "nanim"));
        if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
            nanimStudio.getPreferences().put("lastNanimDirectory", chooser.getCurrentDirectory().getAbsolutePath());
            nanim.open(chooser.getSelectedFile());
            lastFile = chooser.getSelectedFile();
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem_importGIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_importGIFActionPerformed
        JFileChooser chooser = new JFileChooser(nanimStudio.getPreferences().get("lastGifDirectory", null));
        chooser.setFileFilter(new FileNameExtensionFilter("gif animations", "gif", "gif"));
        if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
            nanimStudio.getPreferences().put("lastGifDirectory", chooser.getCurrentDirectory().getAbsolutePath());
            nanim.openGIF(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_jMenuItem_importGIFActionPerformed

    private void jMenuItem_exportGIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exportGIFActionPerformed
        JFileChooser chooser = new JFileChooser(nanimStudio.getPreferences().get("lastGifDirectory", null));
        chooser.setFileFilter(new FileNameExtensionFilter("gif animations", "gif", "gif"));
        if (JFileChooser.APPROVE_OPTION == chooser.showSaveDialog(this)) {
            nanimStudio.getPreferences().put("lastGifDirectory", chooser.getCurrentDirectory().getAbsolutePath());
            nanim.saveGIF(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_jMenuItem_exportGIFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem_exportGIF;
    private javax.swing.JMenuItem jMenuItem_importGIF;
    private javax.swing.JMenuItem jMenuItem_new;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private im.bci.nanimstudio.NframesEditor nFramesEditor1;
    private im.bci.nanimstudio.model.Nanim nanim;
    private im.bci.nanimstudio.NanimationEditor nanimationEditor;
    private im.bci.nanimstudio.NimagesEditor nimagesEditor;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
