/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package im.bci.nanimstudio;

import hu.kazocsaba.imageviewer.ImageViewer;
import im.bci.nanimstudio.model.Nframe;

/**
 *
 * @author bob
 */
public class NframeViewer extends javax.swing.JPanel {

    private final ImageViewer imageViewer;
    private Nframe frame;

    public Nframe getFrame() {
        return frame;
    }

    public void setFrame(Nframe frame) {
        if (null != frame) {
            this.frame = frame;
            imageViewer.setImage(frame.getImage());
        } else {
            this.frame = null;
            imageViewer.setImage(null);
        }
    }

    /**
     * Creates new form NimageViewer
     */
    public NframeViewer() {
        initComponents();
        imageViewer = new ImageViewer();
        imageViewer.setStatusBarVisible(true);
        add(imageViewer.getComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(320, 240));
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
